version: "3.8"

services:
  neo4j: 
    image: neo4j:4.4.0
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins/
      - ./neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/admin
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*

volumes:
  neo4j: